lab/urls.py
from django.urls import path 
from . import views 
urlpatterns = [
    path("", views.dashboard, name="lab_dashboard"),
    path("services_list/", views.ServicesListView.as_view(), name="lab_services_list"),
    path("service_create/", views.ServicesCreate.as_view(), name="lab_service_create"),
    path("service_update/<int:pk>/", views.ServicesUpdate.as_view(),
         name="lab_service_update", ),
    path(
        "service_delete/<int:pk>/",
        views.ServiceDeleteView.as_view(),
        name="lab_service_delete",
    ),
    path("lab_detail/", views.LapDetailListView.as_view(), name="lab_detail"),
    path("lab_detail_create/", views.LabDetailCreate.as_view(), name="lab_detail_create"),
    path("lab_detail_update/<int:pk>/", views.LabDetailUpdate.as_view(),
         name="lab_detail_update", ),
    path(
        "lab_delete/<int:pk>/",
        views.LabDeleteView.as_view(),
        name="lab_detail_delete",
    ),
]

nurse/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name="nurse_dashboard",),
    path(
        "services_list/",
        views.ServicesListView.as_view(),
        name="nurse_services_list",
    ),
    path(
        "service_create/",
        views.ServicesCreate.as_view(),
        name="nurse_service_create",
    ),
    path(
        "service_update/<int:pk>/",
        views.ServicesUpdate.as_view(),
        name="nurse_service_update",
    ),
    path(
        "service_delete/<int:pk>/",
        views.ServiceDeleteView.as_view(),
        name="nurse_service_delete",
    ),
    path(
        "services_times_list/",
        views.ServicesTimesListView.as_view(),
        name="nurse_services_times_list",
    ),
    path(
        "service_time_create/",
        views.ServicesTimesCreate.as_view(),
        name="nurse_service_time_create",
    ),
    path(
        "service_time_update/<int:pk>/",
        views.ServicesTimeUpdate.as_view(),
        name="nurse_service_time_update",
    ),
    path(
        "service_time_delete/<int:pk>/",
        views.ServiceTimeDeleteView.as_view(),
        name="nurse_service_time_delete",
    ),
    path(
        "booking_pending/",
        views.booking_pending,
        name="nurse_booking_pending",
    ),
    path(
        "booking_update/<int:pk>/",
        views.BookingUpdate.as_view(),
        name="nurse_booking_update",
    ),
    path(
        "booking_list/",
        views.booking_list,
        name="nurse_booking_list",
    ),
]

sedrahcare/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    # Main Pages
    path("", include("mobaderapp.pages_urls")),
    path("api/v1/", include("mobaderapp.backend_urls")),
    path("api-auth/", include("rest_framework.urls")),
    # Admin Pages
    path("admin/", include("mobaderapp.admin_urls")),
    path("patient/", include("mobaderapp.patient_urls")),
    path("doctor/", include("mobaderapp.doctor_urls")),
    path("nurse/", include("nurse.urls")),
    path("physio/", include("physiotherapist.urls")),
    path("lab/", include("lab.urls")),
    path("pharma/", include("pharma.urls")),
    path("chatroom/", include("chatroom.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mobaderapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from embed_video.fields import EmbedVideoField


# ===========================================
# Media
class MediaCenter(models.Model):
    title = models.CharField(max_length=200)
    video = EmbedVideoField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("media")


# ===========================================
# Team
class TeamSlider(models.Model):
    image = models.FileField()

    def get_absolute_url(self):
        return reverse("team")


# ===========================================
# Events
class EventSlider(models.Model):
    image = models.FileField()

    def get_absolute_url(self):
        return reverse("event")


# ===========================================
# Doctor Category { القلب ، الامراض الصدريه }
class DoctorCategory(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    url_slug = models.CharField(max_length=200)
    thumbnail = models.FileField()
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("categories_doctor")


# ===========================================
# All Users
class CustomUser(AbstractUser):
    user_type_choices = (
        (1, "Admin"),
        (2, "Staff"),
        (3, "Doctor"),
        (4, "Nurse"),
        (5, "Lap"),
        (6, "Pharmacy"),
        (7, "Physiotherapist"),
        (8, "Patient"),
    )
    user_type = models.CharField(max_length=2, choices=user_type_choices, default=8)
    mobile = models.CharField(max_length=15, default="")


class AdminUser(models.Model):
    auth_user_id = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    profile_pic = models.FileField(default="")
    created_at = models.DateTimeField(auto_now_add=True)


class StaffUser(CustomUser):
    profile_pic = models.FileField(default="")
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("staff_list")


class DoctorUser(CustomUser):
    category_id = models.ForeignKey(
        DoctorCategory,
        on_delete=models.CASCADE,
        related_name="doctor_category",
        null=True,
    )
    profile_pic = models.FileField(default="")
    price = models.FloatField(default=0.0)
    address = models.CharField(max_length=255, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("doctor_list")


class NurseUser(CustomUser):
    profile_pic = models.FileField(default="")
    address = models.CharField(max_length=255, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("nurse_list")


class LapUser(CustomUser):
    profile_pic = models.FileField(default="")
    address = models.CharField(max_length=255, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("lab_list")


class PharmacyUser(CustomUser):
    profile_pic = models.FileField(default="")
    address = models.CharField(max_length=255, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("pharma_list")


class PhysiotherapistUser(CustomUser):
    profile_pic = models.FileField(default="")
    address = models.CharField(max_length=255, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("physio_list")


class PatientUser(CustomUser):
    profile_pic = models.FileField(default="", blank=True, null=True, )
    address = models.CharField(max_length=255, default="")
    verification = models.CharField(max_length=7)
    confirmed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("login")


# =========================================================
# Doctor Times
class DoctorTimes(models.Model):
    id = models.AutoField(primary_key=True)
    doctor = models.ForeignKey(
        DoctorUser,
        on_delete=models.CASCADE,
        related_name="doctor_times",
    )
    title = models.CharField(max_length=200, blank=True)
    start_time = models.DateTimeField(null=True)
    end_time = models.DateTimeField(null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return str(self.start_time)

    @property
    def get_html_url(self):
        url = reverse("appoint_edit", args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'


# ============================================================
# Nurse Service
class NurseService(models.Model):
    id = models.AutoField(primary_key=True)
    nurse = models.ManyToManyField(
        NurseUser
    )
    title = models.CharField(max_length=200)
    details = models.TextField(null=True)
    price = models.FloatField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("nurse_services_list")


class NurseServiceTimes(models.Model):
    id = models.AutoField(primary_key=True)
    nurse = models.ForeignKey(
        NurseUser, on_delete=models.CASCADE, related_name="nurse_id_service"
    )
    service = models.ForeignKey(
        NurseService, on_delete=models.CASCADE, related_name="nurse_service_time"
    )
    day = models.DateField()
    start_time = models.TimeField(null=True)
    end_time = models.TimeField(null=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["-day"]

    def get_absolute_url(self):
        return reverse("nurse_services_times_list")


# ============================================================
# Lap Details
class LabDetail(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.ForeignKey(
        LapUser, on_delete=models.CASCADE, related_name="lap_user"
    )
    name = models.CharField(max_length=250)
    thumbnail = models.FileField()
    description = models.TextField()
    mobile_phone = models.CharField(max_length=15)
    address = models.TextField(null=True)
    open_time = models.TimeField(null=True)
    close_time = models.TimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("lab_detail")


class LabService(models.Model):
    id = models.AutoField(primary_key=True)
    lap = models.ForeignKey(
        LabDetail,
        on_delete=models.CASCADE,
        related_name="lap_service",
    )
    title = models.CharField(max_length=200)
    image = models.FileField(null=True)
    details = models.TextField(null=True)
    price = models.FloatField()

    def get_absolute_url(self):
        return reverse("lab_services_list")


# =============================================================
# Pharmacy Details


class PharmacyDetail(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.ForeignKey(
        PharmacyUser, on_delete=models.CASCADE, related_name="pharmacy_user"
    )
    name = models.CharField(max_length=250)
    thumbnail = models.FileField()
    description = models.TextField()
    mobile_phone = models.CharField(max_length=15)
    address = models.TextField(null=True)
    open_time = models.TimeField(null=True)
    close_time = models.TimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)


class PharmacyMedicine(models.Model):
    id = models.AutoField(primary_key=True)
    pharmacy = models.ForeignKey(
        PharmacyDetail,
        on_delete=models.CASCADE,
        related_name="pharmacy_medicine",
    )
    title = models.CharField(max_length=200)
    count = models.IntegerField(default=1)
    image = models.FileField(null=True)
    details = models.TextField(null=True)
    price = models.FloatField()


# ============================================================
# Physiotherapist Service
class PhysiotherapistService(models.Model):
    id = models.AutoField(primary_key=True)
    physiotherapist = models.ManyToManyField(
        PhysiotherapistUser,
    )
    title = models.CharField(max_length=200)
    details = models.TextField(null=True)
    price = models.FloatField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("physio_services_list")


class PhysiotherapistServiceTimes(models.Model):
    id = models.AutoField(primary_key=True)
    physio = models.ForeignKey(PhysiotherapistUser, on_delete=models.CASCADE)
    service = models.ForeignKey(
        PhysiotherapistService,
        on_delete=models.CASCADE,
        related_name="physio_service_time",
    )
    day = models.DateField()
    start_time = models.TimeField(null=True)
    end_time = models.TimeField(null=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["-day"]

    def get_absolute_url(self):
        return reverse("physio_services_times_list")


# =============================================================
# Patient Booking
class BookDoctor(models.Model):
    class Status(models.TextChoices):
        PENDING = "PEN", "Pending"
        ACCEPTED = "ACC", "Accepted"
        REFUSED = "REF", "Refused"

    class Type(models.TextChoices):
        VISIT = "VISIT", "Visit"
        MEET = "MEET", "Meet"

    id = models.AutoField(primary_key=True)
    patient = models.ForeignKey(
        PatientUser, on_delete=models.CASCADE, related_name="book_doctor"
    )

nurse/models.py
from django.db import models

# Create your models here.

nurse/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.messages.views import SuccessMessageMixin, messages
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from mobaderapp.models import NurseService, NurseUser, NurseServiceTimes, BookNurse
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy


# Create your views here.
def dashboard(request):
    return render(request, "nurse/en/home.html")


class ServicesListView(ListView):
    model = NurseService
    template_name = "nurse/en/service_list.html"


class ServicesCreate(SuccessMessageMixin, CreateView):
    model = NurseService
    success_message = "Service Added!"
    fields = ["title", "details", "price"]
    template_name = "nurse/en/service_create.html"

    def form_valid(self, form):
        service = form.save(commit=False)

        nurse_instance = NurseUser.objects.get(id=self.request.user.id)

        # Save the service instance to get an ID
        service.save()

        # Set the many-to-many relationship
        service.nurse.set([nurse_instance])
        messages.success(self.request, "Service Created Successfully")
        return HttpResponseRedirect(reverse("nurse_services_list"))


class ServicesUpdate(UpdateView):
    model = NurseService
    success_message = "Service Updated!"
    fields = ["title", "details", "price"]
    template_name = "nurse/en/service_update.html"


class ServiceDeleteView(DeleteView):
    model = NurseService
    success_message = "Service Deleted!"
    template_name = "nurse/en/service_delete.html"
    success_url = reverse_lazy("nurse_services_list")


class ServicesTimesListView(ListView):
    model = NurseServiceTimes
    queryset = NurseServiceTimes.objects.filter(
        active=True
    )
    template_name = "nurse/en/service_time_list.html"

    def get_context_data(self, **kwargs):
        context = super(ServicesTimesListView, self).get_context_data(**kwargs)
        context['services'] = NurseService.objects.all()
        return context


class ServicesTimesCreate(SuccessMessageMixin, CreateView):
    model = NurseServiceTimes
    success_message = "Service Added!"
    fields = ["service", "day", "start_time", "end_time"]
    template_name = "nurse/en/service_time_create.html"

    def get_context_data(self, **kwargs):
        context = super(ServicesTimesCreate, self).get_context_data(**kwargs)
        context['services'] = NurseService.objects.all()
        return context

    def form_valid(self, form):
        print(self.request.POST.get('service'))
        service_time = form.save(commit=False)
        service_time.service = NurseService.objects.get(id=self.request.POST.get('service'))
        service_time.nurse = NurseUser.objects.get(id=self.request.user.id)  # Set the nurse_id
        service_time.active = True
        service_time.save()
        messages.success(self.request, "Service Time Created Successfully")
        return HttpResponseRedirect(reverse("nurse_services_times_list"))


class ServicesTimeUpdate(UpdateView):
    model = NurseServiceTimes
    success_message = "Service Time Updated!"
    fields = ["day", "start_time", "end_time"]
    template_name = "nurse/en/service_time_update.html"


class ServiceTimeDeleteView(DeleteView):
    model = NurseServiceTimes
    success_message = "Service Deleted!"
    template_name = "nurse/en/service_time_delete.html"
    success_url = reverse_lazy("nurse_services_times_list")


# Bookings
def booking_pending(request):
    context = {}
    nurse = NurseUser.objects.get(
        id=request.user.id
    )
    book_nurse = BookNurse.objects.filter(
        nurse_id=nurse.id,
        status="PEN"
    )
    context['booknurse'] = book_nurse
    return render(request, "nurse/en/booking_pending.html", context)


def booking_list(request):
    context = {}
    nurse = NurseUser.objects.get(
        id=request.user.id
    )
    book_nurse = BookNurse.objects.filter(
        nurse_id=nurse.id
    )
    context['booknurse'] = book_nurse
    return render(request, "nurse/en/all_booking.html", context)


class BookingUpdate(UpdateView):
    model = BookNurse
    success_message = "Book Updated!"
    fields = ["status"]
    template_name = "nurse/en/booking_update.html"

nurse/templates/nurse/en/all_booking.html
{% extends 'nurse/en/base_template.html' %}
{% load static %}

<!-- BLOCK FOR TITLE-->
{% block title %}
All Bookings
{% endblock title %}
<!-- END BLOCK FOR TITLE-->

<!-- BLOCK FOR CUSTOM CSS-->
{% block custom_css %}
<link rel="stylesheet" href="{% static '/pages/css/home_en.css' %}">
{% endblock custom_css %}
<!-- END BLOCK FOR CUSTOM CSS-->

<!-- BLOCK FOR PAGE TITLE-->
{% block page_title %}
All Bookings
{% endblock page_title %}
<!-- END BLOCK FOR PAGE TITLE-->

<!-- BLOCK FOR PAGE MAIN CONTENT-->
{% block page_content %}

    <div class="row">
        {% for book in booknurse %}
        <div class="col-12 col-sm-6 col-md-6 col-lg-3">
            <article class="article article-style-b">
                <div class="article-header">
                    <div class="article-image" data-background="{{book.patient.profile_pic}}"></div>
                    <div class="article-badge">
                        <div class="article-badge-item bg-danger">
                            <i class="fas fa-fire"></i>
                            {{ book.patient.auth_user_id }}
                        </div>
                    </div>
                </div>
                <div class="article-details">
                    <p><span class="badge badge-{% if book.status == 'ACC'%}primary{% elif book.status == 'PEN' %}warning{% else %}danger{%endif%}">Status: {% if book.status == "ACC"%}Accepted{% elif book.status == "PEN" %}Pending{% else %}Refused{%endif%}</span></p>
                    <p>Day: {{ book.time.day }}</p>
                    <p>Time: {{ book.time.start_time }}</p>
    
                </div>
            </article>
        </div>
        {% endfor %}
    </div>

{% endblock page_content %}
<!-- END BLOCK FOR PAGE MAIN CONTENT-->

<!-- BLOCK FOR CUSTOM JS-->
{% block custom_js %}
{% endblock custom_js %}
<!-- END BLOCK FOR CUSTOM JS-->

nurse/templates/nurse/en/base_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no"
      name="viewport"
    />
    <title>
      {% block title %} 
      {% endblock title %}
    </title>

    <!-- General CSS Files -->
    <link
      rel="stylesheet"
      href="{% static '/modules/bootstrap/css/bootstrap.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static '/modules/fontawesome/css/all.min.css' %}"
    />

    <!-- CSS Libraries -->
    <link
      rel="stylesheet"
      href="{% static '/modules/jqvmap/dist/jqvmap.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static '/modules/weather-icon/css/weather-icons.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static '/modules/weather-icon/css/weather-icons-wind.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static '/modules/summernote/summernote-bs4.css' %}"
    />

    <!-- Template CSS -->
    <link rel="stylesheet" href="{% static '/css/style.css' %}" />
    <link rel="stylesheet" href="{% static '/css/components.css' %}" />

    {% block custom_css %} 
    {% endblock custom_css %}

    <style>
      ul.errorlist {
        margin: 0px;
      }
    </style>
  </head>

  <body>
    <div id="app">
      <div class="main-wrapper main-wrapper-1">
        {% include 'nurse/en/navbar.html' %}
        {% include 'nurse/en/sidebar.html' with id=form.instance.id %}
        <!-- Main Content -->
        <div class="main-content">
          <section class="section">
            <div class="section-header">
              <h1>
                {% block page_title %} 
                {% endblock page_title %}
              </h1>
            </div>
            {% if messages %} 
            {% for message in messages %} 
            {% if message.tags == "success" %}
            <div class="alert alert-success alert-dismissible show fade">
              <div class="alert-body">
                <button class="close" data-dismiss="alert">
                  <span>×</span>
                </button>
                {{ message }}
              </div>
            </div>
            {% endif %} 
            {% if message.tags == "error" %}
            <div class="alert alert-error">{{ message }}</div>
            {% endif %} 
            {% endfor %} 
            {% endif %} 
            {% block page_content %} 
            {% endblock page_content %}
          </section>
        </div>

      </div>
    </div>

    <!-- General JS Scripts -->
    <script src="{% static '/modules/jquery.min.js' %}"></script>
    <script src="{% static '/modules/popper.js' %}"></script>
    <script src="{% static '/modules/tooltip.js' %}"></script>
    <script src="{% static '/modules/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/modules/nicescroll/jquery.nicescroll.min.js' %}"></script>
    <script src="{% static '/modules/moment.min.js' %}"></script>
    <script src="{% static '/js/stisla.js' %}"></script>

    <!-- JS Libraies -->
    <script src="{% static '/modules/simple-weather/jquery.simpleWeather.min.js' %}"></script>
    <script src="{% static '/modules/chart.min.js' %}"></script>
    <script src="{% static '/modules/jqvmap/dist/jquery.vmap.min.js' %}"></script>
    <script src="{% static '/modules/jqvmap/dist/maps/jquery.vmap.world.js' %}"></script>
    <script src="{% static '/modules/summernote/summernote-bs4.js' %}"></script>
    <script src="{% static '/modules/chocolat/dist/js/jquery.chocolat.min.js' %}"></script>

    <!-- Page Specific JS File -->
    <script src="{% static '/js/page/index-0.js' %}"></script>

    <!-- Template JS File -->
    <script src="{% static '/js/scripts.js' %}"></script>
    <script src="{% static '/js/custom.js' %}"></script>
    {% block custom_js %} {% endblock custom_js %}
    <script>
      document.getElementById("title").onkeyup = function () {
        document.getElementById("url_slug").value = document
          .getElementById("title")
          .value.toLowerCase()
          .replace(" ", "-");
      };
    </script>
  </body>
<footer>
  Copyright &copy; 2024
  Design By <a href="https://sdcadv.sa/">SDC</a>
</footer>
</html>

nurse/templates/nurse/en/booking_pending.html
{% extends 'nurse/en/base_template.html' %}
{% load static %}

<!-- BLOCK FOR TITLE-->
{% block title %}
Pending Bookings
{% endblock title %}
<!-- END BLOCK FOR TITLE-->

<!-- BLOCK FOR CUSTOM CSS-->
{% block custom_css %}
<link rel="stylesheet" href="{% static '/pages/css/home_en.css' %}">
{% endblock custom_css %}
<!-- END BLOCK FOR CUSTOM CSS-->

<!-- BLOCK FOR PAGE TITLE-->
{% block page_title %}
Pending Bookings
{% endblock page_title %}
<!-- END BLOCK FOR PAGE TITLE-->

<!-- BLOCK FOR PAGE MAIN CONTENT-->
{% block page_content %}

    <div class="row">
        {% for book in booknurse %}
        <div class="col-12 col-sm-6 col-md-6 col-lg-3">
            <article class="article article-style-b">
                <div class="article-header">
                    <div class="article-image" data-background="{{book.patient.profile_pic}}"></div>
                    <div class="article-badge">
                        <div class="article-badge-item bg-danger">
                            <i class="fas fa-fire"></i>
                            {{ book.patient.auth_user_id }}
                        </div>
                    </div>
                </div>
                <div class="article-details">
                    <p><span class="badge badge-{% if book.status == 'ACC'%}primary{% elif book.status == 'PEN' %}warning{% else %}danger{%endif%}">Status: {% if book.status == "ACC"%}Accepted{% elif book.status == "PEN" %}Pending{% else %}Refused{%endif%}</span></p>
                    <p>Day: {{ book.time.day }}</p>
                    <p>Time: {{ book.time.start_time }}</p>
                    <div class="article-cta">
                        <a href="{% url 'nurse_booking_update' book.id %}" class="btn btn-warning">
                            EDIT
                            <i class="fas fa-chevron-right"></i>
                        </a>
                    </div>
    
                </div>
                
            </article>
        </div>
        {% endfor %}
    </div>

{% endblock page_content %}
<!-- END BLOCK FOR PAGE MAIN CONTENT-->

<!-- BLOCK FOR CUSTOM JS-->
{% block custom_js %}
{% endblock custom_js %}
<!-- END BLOCK FOR CUSTOM JS-->

nurse/templates/nurse/en/home.html
{% extends 'nurse/en/base_template.html' %}
{% load static %}

<!-- BLOCK FOR TITLE-->
{% block title %}
Nurse Home
{% endblock title %}
<!-- END BLOCK FOR TITLE-->

<!-- BLOCK FOR CUSTOM CSS-->
{% block custom_css %}
<link rel="stylesheet" href="{% static '/modules/fullcalendar/fullcalendar.min.css' %}">
{% endblock custom_css %}
<!-- END BLOCK FOR CUSTOM CSS-->

<!-- BLOCK FOR PAGE TITLE-->
{% block page_title %}
Nurse Home
{% endblock page_title %}
<!-- END BLOCK FOR PAGE TITLE-->

<!-- BLOCK FOR PAGE MAIN CONTENT-->
{% block page_content %}
<!-- Reports All Users-->
<div class="row">
    
</div>
{% endblock page_content %}
<!-- END BLOCK FOR PAGE MAIN CONTENT-->

<!-- BLOCK FOR CUSTOM JS-->
{% block custom_js %}
{% endblock custom_js %}
<!-- END BLOCK FOR CUSTOM JS-->

nurse/templates/nurse/en/service_list.html
{% extends 'nurse/en/base_template.html' %}

<!-- BLOCK FOR TITLE-->
{% block title %} Service List {% endblock title %}
<!-- END BLOCK FOR TITLE-->

<!-- BLOCK FOR CUSTOM CSS-->
{% block custom_css %} {% endblock custom_css %}
<!-- END BLOCK FOR CUSTOM CSS-->

<!-- BLOCK FOR PAGE TITLE-->
{% block page_title %}
Service List
{% endblock page_title %}
<!-- END BLOCK FOR PAGE TITLE-->

<!-- BLOCK FOR PAGE MAIN CONTENT-->
{% block page_content %}
<div class="row">
    {% for service in nurseservice_list %}
    <div class="col-12 col-sm-6 col-md-6 col-lg-3">
        <article class="article article-style-b">
            <div class="article-details">
                <h4>{{ service.title }}</h4>
                <p>{{ service.details }}</p>
                <p><span class="badge badge-primary">Price: {{ service.price }} SAR</span></p>
                <div class="article-cta">
                    <a href="{% url 'nurse_service_update' service.id %}" class="btn btn-warning">
                        EDIT
                        <i class="fas fa-chevron-right"></i>
                    </a>
                    <a href="{% url 'nurse_service_delete' service.id %}" class="btn btn-danger">
                        Delete
                        <i class="fas fa-chevron-right"></i>
                    </a>
                </div>
            </div>
        </article>
    </div>

    {% endfor %}

</div>
{% endblock page_content %}
<!-- END BLOCK FOR PAGE MAIN CONTENT-->

<!-- BLOCK FOR CUSTOM JS-->
{% block custom_js %} {% endblock custom_js %}
<!-- END BLOCK FOR CUSTOM JS-->