lab/urls.py
from django.urls import path 
from . import views 
urlpatterns = [
    path("", views.dashboard, name="lab_dashboard"),
    path("services_list/", views.ServicesListView.as_view(), name="lab_services_list"),
    path("service_create/", views.ServicesCreate.as_view(), name="lab_service_create"),
    path("service_update/<int:pk>/", views.ServicesUpdate.as_view(),
         name="lab_service_update", ),
    path(
        "service_delete/<int:pk>/",
        views.ServiceDeleteView.as_view(),
        name="lab_service_delete",
    ),
    path("lab_detail/", views.LapDetailListView.as_view(), name="lab_detail"),
    path("lab_detail_create/", views.LabDetailCreate.as_view(), name="lab_detail_create"),
    path("lab_detail_update/<int:pk>/", views.LabDetailUpdate.as_view(),
         name="lab_detail_update", ),
    path(
        "lab_delete/<int:pk>/",
        views.LabDeleteView.as_view(),
        name="lab_detail_delete",
    ),
]

sedrahcare/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    # Main Pages
    path("", include("mobaderapp.pages_urls")),
    path("api/v1/", include("mobaderapp.backend_urls")),
    path("api-auth/", include("rest_framework.urls")),
    # Admin Pages
    path("admin/", include("mobaderapp.admin_urls")),
    path("patient/", include("mobaderapp.patient_urls")),
    path("doctor/", include("mobaderapp.doctor_urls")),
    path("nurse/", include("nurse.urls")),
    path("physio/", include("physiotherapist.urls")),
    path("lab/", include("lab.urls")),
    path("pharma/", include("pharma.urls")),
    path("chatroom/", include("chatroom.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mobaderapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from embed_video.fields import EmbedVideoField


# ===========================================
# Media
class MediaCenter(models.Model):
    title = models.CharField(max_length=200)
    video = EmbedVideoField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("media")


# ===========================================
# Team
class TeamSlider(models.Model):
    image = models.FileField()

    def get_absolute_url(self):
        return reverse("team")


# ===========================================
# Events
class EventSlider(models.Model):
    image = models.FileField()

    def get_absolute_url(self):
        return reverse("event")


# ===========================================
# Doctor Category { القلب ، الامراض الصدريه }
class DoctorCategory(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    url_slug = models.CharField(max_length=200)
    thumbnail = models.FileField()
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("categories_doctor")


# ===========================================
# All Users
class CustomUser(AbstractUser):
    user_type_choices = (
        (1, "Admin"),
        (2, "Staff"),
        (3, "Doctor"),
        (4, "Nurse"),
        (5, "Lap"),
        (6, "Pharmacy"),
        (7, "Physiotherapist"),
        (8, "Patient"),
    )
    user_type = models.CharField(max_length=2, choices=user_type_choices, default=8)
    mobile = models.CharField(max_length=15, default="")


class AdminUser(models.Model):
    auth_user_id = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    profile_pic = models.FileField(default="")
    created_at = models.DateTimeField(auto_now_add=True)


class StaffUser(CustomUser):
    profile_pic = models.FileField(default="")
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("staff_list")


class DoctorUser(CustomUser):
    category_id = models.ForeignKey(
        DoctorCategory,
        on_delete=models.CASCADE,
        related_name="doctor_category",
        null=True,
    )
    profile_pic = models.FileField(default="")
    price = models.FloatField(default=0.0)
    address = models.CharField(max_length=255, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("doctor_list")


class NurseUser(CustomUser):
    profile_pic = models.FileField(default="")
    address = models.CharField(max_length=255, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("nurse_list")


class LapUser(CustomUser):
    profile_pic = models.FileField(default="")
    address = models.CharField(max_length=255, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("lab_list")


class PharmacyUser(CustomUser):
    profile_pic = models.FileField(default="")
    address = models.CharField(max_length=255, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("pharma_list")


class PhysiotherapistUser(CustomUser):
    profile_pic = models.FileField(default="")
    address = models.CharField(max_length=255, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("physio_list")


class PatientUser(CustomUser):
    profile_pic = models.FileField(default="", blank=True, null=True, )
    address = models.CharField(max_length=255, default="")
    verification = models.CharField(max_length=7)
    confirmed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("login")


# =========================================================
# Doctor Times
class DoctorTimes(models.Model):
    id = models.AutoField(primary_key=True)
    doctor = models.ForeignKey(
        DoctorUser,
        on_delete=models.CASCADE,
        related_name="doctor_times",
    )
    title = models.CharField(max_length=200, blank=True)
    start_time = models.DateTimeField(null=True)
    end_time = models.DateTimeField(null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return str(self.start_time)

    @property
    def get_html_url(self):
        url = reverse("appoint_edit", args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'


# ============================================================
# Nurse Service
class NurseService(models.Model):
    id = models.AutoField(primary_key=True)
    nurse = models.ManyToManyField(
        NurseUser
    )
    title = models.CharField(max_length=200)
    details = models.TextField(null=True)
    price = models.FloatField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("nurse_services_list")


class NurseServiceTimes(models.Model):
    id = models.AutoField(primary_key=True)
    nurse = models.ForeignKey(
        NurseUser, on_delete=models.CASCADE, related_name="nurse_id_service"
    )
    service = models.ForeignKey(
        NurseService, on_delete=models.CASCADE, related_name="nurse_service_time"
    )
    day = models.DateField()
    start_time = models.TimeField(null=True)
    end_time = models.TimeField(null=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["-day"]

    def get_absolute_url(self):
        return reverse("nurse_services_times_list")


# ============================================================
# Lap Details
class LabDetail(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.ForeignKey(
        LapUser, on_delete=models.CASCADE, related_name="lap_user"
    )
    name = models.CharField(max_length=250)
    thumbnail = models.FileField()
    description = models.TextField()
    mobile_phone = models.CharField(max_length=15)
    address = models.TextField(null=True)
    open_time = models.TimeField(null=True)
    close_time = models.TimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("lab_detail")


class LabService(models.Model):
    id = models.AutoField(primary_key=True)
    lap = models.ForeignKey(
        LabDetail,
        on_delete=models.CASCADE,
        related_name="lap_service",
    )
    title = models.CharField(max_length=200)
    image = models.FileField(null=True)
    details = models.TextField(null=True)
    price = models.FloatField()

    def get_absolute_url(self):
        return reverse("lab_services_list")


# =============================================================
# Pharmacy Details


class PharmacyDetail(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.ForeignKey(
        PharmacyUser, on_delete=models.CASCADE, related_name="pharmacy_user"
    )
    name = models.CharField(max_length=250)
    thumbnail = models.FileField()
    description = models.TextField()
    mobile_phone = models.CharField(max_length=15)
    address = models.TextField(null=True)
    open_time = models.TimeField(null=True)
    close_time = models.TimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)


class PharmacyMedicine(models.Model):
    id = models.AutoField(primary_key=True)
    pharmacy = models.ForeignKey(
        PharmacyDetail,
        on_delete=models.CASCADE,
        related_name="pharmacy_medicine",
    )
    title = models.CharField(max_length=200)
    count = models.IntegerField(default=1)
    image = models.FileField(null=True)
    details = models.TextField(null=True)
    price = models.FloatField()


# ============================================================
# Physiotherapist Service
class PhysiotherapistService(models.Model):
    id = models.AutoField(primary_key=True)
    physiotherapist = models.ManyToManyField(
        PhysiotherapistUser,
    )
    title = models.CharField(max_length=200)
    details = models.TextField(null=True)
    price = models.FloatField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("physio_services_list")


class PhysiotherapistServiceTimes(models.Model):
    id = models.AutoField(primary_key=True)
    physio = models.ForeignKey(PhysiotherapistUser, on_delete=models.CASCADE)
    service = models.ForeignKey(
        PhysiotherapistService,
        on_delete=models.CASCADE,
        related_name="physio_service_time",
    )
    day = models.DateField()
    start_time = models.TimeField(null=True)
    end_time = models.TimeField(null=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["-day"]

    def get_absolute_url(self):
        return reverse("physio_services_times_list")


# =============================================================
# Patient Booking
class BookDoctor(models.Model):
    class Status(models.TextChoices):
        PENDING = "PEN", "Pending"
        ACCEPTED = "ACC", "Accepted"
        REFUSED = "REF", "Refused"

    class Type(models.TextChoices):
        VISIT = "VISIT", "Visit"
        MEET = "MEET", "Meet"

    id = models.AutoField(primary_key=True)
    patient = models.ForeignKey(
        PatientUser, on_delete=models.CASCADE, related_name="book_doctor"
    )

mobaderapp/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.forms import ModelForm, DateInput

from .models import (
    DoctorTimes,
    BookDoctor,
    BookNurse,
    BookPhysio,
    BookAnalytic,
    BookMedicine,
    PatientUser,
    CustomUser,
)

# a RegexValidator for the mobile phone number
mobile_validator = RegexValidator(
    regex=r'^[1-9]\d{8}$',
    message='Enter a valid mobile number!',
)


# Register
class PatientUserForm(forms.ModelForm):
    mobile = forms.CharField(validators=[mobile_validator])

    class Meta:
        model = PatientUser
        fields = ["mobile", "username", "email", "password"]


# class UserRegistrationForm(forms.ModelForm):
# password = forms.CharField(label="Password", widget=forms.PasswordInput)
#
# class Meta:
#     model = CustomUser
#     fields = ["username", "email", "password"]
#
# def clean_phone_number(self):
#     phone_number = self.cleaned_data["phone_number"]
#     phone_number_processed = re.match("^\+?(\d+)$", phone_number)
#     if phone_number_processed and len(phone_number_processed[1]) >= 9:
#         if len(phone_number_processed[1]) == 9:
#             return phone_number_processed[1]
#
#         phone_number_stripped = re.match("^966(\d{9})$", phone_number_processed[1])
#         if phone_number_stripped:
#             return phone_number_stripped[1]
#     raise forms.ValidationError("Invalid Phone Number. Must satisfy: +966123456789")


# Login for all users
class LoginForm(forms.Form):
    mobile = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class EventForm(ModelForm):
    class Meta:
        model = DoctorTimes
        widgets = {
            "start_time": DateInput(
                attrs={"type": "datetime-local"}, format="%Y-%m-%dT%H:%M"
            ),
            "end_time": DateInput(
                attrs={"type": "datetime-local"}, format="%Y-%m-%dT%H:%M"
            ),
        }
        fields = ["title", "start_time", "end_time"]

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields["start_time"].input_formats = ("%Y-%m-%dT%H:%M",)
        self.fields["end_time"].input_formats = ("%Y-%m-%dT%H:%M",)


class ServiceVisitBooking(ModelForm):
    class Meta:
        model = BookDoctor
        fields = "__all__"

    def clean_patient_address(self):
        print("Finish Service")
        patient_addr = self.cleaned_data["patient_address"]
        if patient_addr != "":
            return patient_addr
        raise forms.ValidationError("Invalid Address")


class ServiceVisitBookingNurse(ModelForm):
    class Meta:
        model = BookNurse
        fields = "__all__"


class ServiceVisitBookingPhysio(ModelForm):
    class Meta:
        model = BookPhysio
        fields = "__all__"


class ServiceVisitBookingAnalytic(ModelForm):
    class Meta:
        model = BookAnalytic
        fields = "__all__"


class ServiceVisitBookingMedicine(ModelForm):
    class Meta:
        model = BookMedicine
        fields = "__all__"

mobaderapp/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from .forms import LoginForm


def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request,
                mobile=cd["mobile"],
                password=cd["password"],
            )
            if user is not None:
                if user.is_active:
                    login(request, user)
                    if user.user_type == "1":
                        return HttpResponseRedirect(reverse("admin_home"))
                    if user.user_type == "2":
                        return HttpResponseRedirect(reverse("home_ar"))
                    if user.user_type == "3":
                        return HttpResponseRedirect(reverse("doctor_dashboard"))
                    if user.user_type == "4":
                        return HttpResponseRedirect(reverse("nurse_dashboard"))
                    if user.user_type == "5":
                        return HttpResponseRedirect(reverse("lab_dashboard"))
                    if user.user_type == "6":
                        return HttpResponseRedirect(reverse("pharma_dashboard"))
                    if user.user_type == "7":
                        return HttpResponseRedirect(reverse("physio_dashboard"))
                    if user.user_type == "8":
                        return HttpResponseRedirect(reverse("patient_dashboard"))
            else:
                messages.error(request, "Error in Login! Invalid Login Details ")
                return render(request, "en/pages/signin.html", {"form": form})
    else:
        form = LoginForm()
    return render(request, "en/pages/signin.html", {"form": form})


def users_logout_process(request):
    logout(request)
    messages.success(request, "Logout Successfully!")
    return HttpResponseRedirect(reverse("home_ar"))

mobaderapp/templates/en/admin/category_create.html
{% extends 'en/admin/base_template.html' %}

<!-- BLOCK FOR TITLE-->
{% block title %} Category Create {% endblock title %}
<!-- END BLOCK FOR TITLE-->

<!-- BLOCK FOR CUSTOM CSS-->
{% block custom_css %} {% endblock custom_css %}
<!-- END BLOCK FOR CUSTOM CSS-->

<!-- BLOCK FOR PAGE TITLE-->
{% block page_title %}
New Doctor Category
{% endblock page_title %}
<!-- END BLOCK FOR PAGE TITLE-->

<!-- BLOCK FOR PAGE MAIN CONTENT-->
{% block page_content %}
<div class="row">
    <div class="col-12 col-md-12 col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4>New Doctor Category</h4>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <label>{{ field.label }}</label>
                        <input
                                type="{{ field.field.widget.input_type }}"
                                name="{{ field.name }}"
                                id="{{ field.name }}"
                                class="form-control"/>
                    </div>
                    {% if field.errors%}
                    <div class="alert alert-danger" style="margin: 10px">
                        {{ field.errors }}
                    </div>
                    {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">
                        SAVE CATEGORY
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock page_content %}
<!-- END BLOCK FOR PAGE MAIN CONTENT-->

<!-- BLOCK FOR CUSTOM JS-->
{% block custom_js %} {% endblock custom_js %}
<!-- END BLOCK FOR CUSTOM JS-->

mobaderapp/templates/en/admin/category_update.html
{% extends 'en/admin/base_template.html' %}

<!-- BLOCK FOR TITLE-->
{% block title %} Category Update {% endblock title %}
<!-- END BLOCK FOR TITLE-->

<!-- BLOCK FOR CUSTOM CSS-->
{% block custom_css %} {% endblock custom_css %}
<!-- END BLOCK FOR CUSTOM CSS-->

<!-- BLOCK FOR PAGE TITLE-->
{% block page_title %} Category Update {% endblock page_title %}
<!-- END BLOCK FOR PAGE TITLE-->

<!-- BLOCK FOR PAGE MAIN CONTENT-->
{% block page_content %}
<div class="row">
    <div class="col-12 col-md-12 col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4>Categories</h4>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <label>{{ field.label }}</label>
                        <input
                                type="{{ field.field.widget.input_type }}"
                                name="{{ field.name }}"
                                id="{{ field.name }}"
                                class="form-control"
                                value="{{ field.value }}"
                        />
                        {% if field.errors%}
                        <div class="alert alert-danger" style="margin: 10px">
                            {{ field.errors }}
                        </div>
                        {% endif %}
                    </div>
                    {% if field.field.widget.input_type == "file" %}
                    <div class="form-group">
                        <label>Current {{field.label}}</label><br>
                        <div class="card">
                            <div class="card-body">
                                <img src="/media/{{field.value}}" style="height:250px"/>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary btn-block">
                        UPDATE CATEGORY
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock page_content %}
<!-- END BLOCK FOR PAGE MAIN CONTENT-->

<!-- BLOCK FOR CUSTOM JS-->
{% block custom_js %} {% endblock custom_js %}
<!-- END BLOCK FOR CUSTOM JS-->

mobaderapp/templates/en/admin/event_create.html
{% extends 'en/admin/base_template.html' %}

<!-- BLOCK FOR TITLE-->
{% block title %} Event Create {% endblock title %}
<!-- END BLOCK FOR TITLE-->

<!-- BLOCK FOR CUSTOM CSS-->
{% block custom_css %} {% endblock custom_css %}
<!-- END BLOCK FOR CUSTOM CSS-->

<!-- BLOCK FOR PAGE TITLE-->
{% block page_title %}
    Event
{% endblock page_title %}
<!-- END BLOCK FOR PAGE TITLE-->

<!-- BLOCK FOR PAGE MAIN CONTENT-->
{% block page_content %}
    <div class="row">
        <div class="col-12 col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h4>New Event</h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label>{{ field.label }}</label>
                                <input
                                        type="{{ field.field.widget.input_type }}"
                                        name="{{ field.name }}"
                                        id="{{ field.name }}"
                                        class="form-control"/>
                            </div>
                            {% if field.errors %}
                                <div class="alert alert-danger" style="margin: 10px">
                                    {{ field.errors }}
                                </div>
                            {% endif %}
                        {% endfor %}
                        <button type="submit" class="btn btn-primary btn-block">
                            SAVE Event
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock page_content %}
<!-- END BLOCK FOR PAGE MAIN CONTENT-->

<!-- BLOCK FOR CUSTOM JS-->
{% block custom_js %} {% endblock custom_js %}
<!-- END BLOCK FOR CUSTOM JS-->

mobaderapp/templates/en/admin/home.html
{% extends 'en/admin/base_template.html' %}
{% load static %}

<!-- BLOCK FOR TITLE-->
{% block title %}
Dashboard
{% endblock title %}
<!-- END BLOCK FOR TITLE-->

<!-- BLOCK FOR CUSTOM CSS-->
{% block custom_css %}
{% endblock custom_css %}
<!-- END BLOCK FOR CUSTOM CSS-->

<!-- BLOCK FOR PAGE TITLE-->
{% block page_title %}
Dashboard
{% endblock page_title %}
<!-- END BLOCK FOR PAGE TITLE-->

<!-- BLOCK FOR PAGE MAIN CONTENT-->
{% block page_content %}
<!-- Reports All Users-->
<div class="row">
    <!--Staff-->
    <div class="col-lg-3 col-md-6 col-sm-6 col-12">
        <div class="card card-statistic-1">
            <div class="card-icon bg-primary">
                <i class="fas fa-user-ninja"></i>
            </div>
            <div class="card-wrap">
                <div class="card-header">
                    <h4>Staff</h4>
                </div>
                <div class="card-body">
                    {{num_staff}}
                </div>
            </div>
        </div>
    </div>
    <!--Doctors-->
    <div class="col-lg-3 col-md-6 col-sm-6 col-12">
        <div class="card card-statistic-1">
            <div class="card-icon bg-danger">
                <i class="fas fa-user-md"></i>
            </div>
            <div class="card-wrap">
                <div class="card-header">
                    <h4>Doctors</h4>
                </div>
                <div class="card-body">
                    {{num_doctors}}
                </div>
            </div>
        </div>
    </div>
    <!--Nurse-->
    <div class="col-lg-3 col-md-6 col-sm-6 col-12">
        <div class="card card-statistic-1">
            <div class="card-icon bg-warning">
                <i class="fas fa-user-graduate"></i>
            </div>
            <div class="card-wrap">
                <div class="card-header">
                    <h4>Nurses</h4>
                </div>
                <div class="card-body">
                    {{num_nurses}}
                </div>
            </div>
        </div>
    </div>
    <!--Physiotherapist-->
    <div class="col-lg-3 col-md-6 col-sm-6 col-12">
        <div class="card card-statistic-1">
            <div class="card-icon bg-success">
                <i class="fas fa-walking"></i>
            </div>
            <div class="card-wrap">
                <div class="card-header">
                    <h4>Physiotherapist</h4>
                </div>
                <div class="card-body">
                    {{num_physiotherapist}}
                </div>
            </div>
        </div>
    </div>
    <!--Laboratory-->
    <div class="col-lg-3 col-md-6 col-sm-6 col-12">
        <div class="card card-statistic-1">
            <div class="card-icon bg-primary">
                <i class="fas fa-microscope"></i>
            </div>
            <div class="card-wrap">
                <div class="card-header">
                    <h4>Laboratory</h4>
                </div>
                <div class="card-body">
                    {{num_laps}}
                </div>
            </div>
        </div>
    </div>
    <!--Pharmacy-->
    <div class="col-lg-3 col-md-6 col-sm-6 col-12">
        <div class="card card-statistic-1">
            <div class="card-icon bg-danger">
                <i class="fas fa-vial"></i>
            </div>
            <div class="card-wrap">
                <div class="card-header">
                    <h4>Pharmacy</h4>
                </div>
                <div class="card-body">
                    {{num_pharmacy}}
                </div>
            </div>
        </div>
    </div>
    <!--Patient-->
    <div class="col-lg-3 col-md-6 col-sm-6 col-12">
        <div class="card card-statistic-1">
            <div class="card-icon bg-warning">
                <i class="fas fa-user-plus"></i>
            </div>
            <div class="card-wrap">
                <div class="card-header">
                    <h4>Patient</h4>
                </div>
                <div class="card-body">
                    {{num_patients}}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock page_content %}
<!-- END BLOCK FOR PAGE MAIN CONTENT-->

<!-- BLOCK FOR CUSTOM JS-->
{% block custom_js %}
{% endblock custom_js %}
<!-- END BLOCK FOR CUSTOM JS-->

mobaderapp/templates/en/admin/media_list.html
{% extends 'en/admin/base_template.html' %}

<!-- BLOCK FOR TITLE-->
{% block title %} Media List {% endblock title %}
<!-- END BLOCK FOR TITLE-->

<!-- BLOCK FOR CUSTOM CSS-->
{% block custom_css %} {% endblock custom_css %}
<!-- END BLOCK FOR CUSTOM CSS-->

<!-- BLOCK FOR PAGE TITLE-->
{% block page_title %}
    Media List
{% endblock page_title %}
<!-- END BLOCK FOR PAGE TITLE-->

<!-- BLOCK FOR PAGE MAIN CONTENT-->
{% block page_content %}
    <div class="row">
        {% for media in mediacenter_list %}
            <div class="col-12 col-sm-6 col-md-6 col-lg-3">
                <article class="article article-style-b">
                    <div class="article-header">
                        <iframe width="100%" height="250rem"
                        src="{{ media.video }}" title="YouTube video player"
                        frameborder="2"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        allowfullscreen></iframe>
                    </div>
                    <div class="article-details">
                        <p>{{ media.title }}</p>
                        <div class="article-cta">
                            <a href="{% url 'media_update' media.id %}" class="btn btn-warning">
                                EDIT
                                <i class="fas fa-chevron-right"></i>
                            </a>
                            <a href="{% url 'media_delete' media.id %}" class="btn btn-danger">
                                Delete
                                <i class="fas fa-chevron-right"></i>
                            </a>
                        </div>
                    </div>
                </article>
            </div>

        {% endfor %}

    </div>
{% endblock page_content %}
<!-- END BLOCK FOR PAGE MAIN CONTENT-->

<!-- BLOCK FOR CUSTOM JS-->
{% block custom_js %} {% endblock custom_js %}
<!-- END BLOCK FOR CUSTOM JS-->